### ISSUE TITLE
Test Groot for Windows 

### ISSUE THREAD

**Issue by omi10859** [omi10859/jarvis#12]
Groot is not tested for Windows machine

test for Linux machine
If some requirement needs to be updated
update here: https://github.com/omi10859/GROOT/blob/master/requirements/requirements-win.txt

Need help ping me!

**Comment by zephyrzilla** [comment]
Taking this issue up.

**Comment by omi10859** [comment]
Status @surajit-techie ?

**Comment by Ifyokoh** [comment]
Is this still open?

**Comment by omi10859** [comment]
yeah, it is.

**Comment by shubhamkragrawal** [comment]
i'll take this issue.

**Comment by omi10859** [comment]
Go Ahead!

**Comment by BhanuPrakashNani** [comment]
Any updates over this issue?

**Comment by nikhilmehta011** [comment]
Successfully tested groot on windows machine. Both video and gif is provided below
[Testing_windows.zip](https://github.com/omi10859/GROOT/files/2942163/Testing_windows.zip)
![testing_windows](https://user-images.githubusercontent.com/35212721/53970964-e39db300-4121-11e9-85dc-da775a7a4d40.gif)

**Comment by BhanuPrakashNani** [comment]
It seems fine in Windows. Did you find any difficulties before it worked properly? Any more requirements needed?

**Comment by nikhilmehta011** [comment]
Before Mic was freezing. No, no need for any other requirements.

**Comment by BhanuPrakashNani** [comment]
Now the Mic works fine? If yes then we can move forward and close this issue as it works perfectly as per the video. Thank you.
