### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by omi10859** [omi10859/jarvis#13]
Readme File needs to be updated with more about Groot and how someone can use Groot. 
Some of the points are already here if you want something else you can add.
- Add **What is Groot?**
- What **Groot can do?**
- **How to run Groot?**
- **How to contribute**

Need help? I'm free

**Comment by akshat0047** [comment]
Taking this issue!

**Comment by yeshijinsel** [comment]
can I take this issue

**Comment by omi10859** [comment]
@akshat0047 waiting for PR

**Comment by yeshijinsel** [comment]
can I do make PR on this
