### ISSUE TITLE
Porting GUI to PyQt5

### ISSUE THREAD

**Issue by nikhilmehta011** [omi10859/jarvis#20]
Groot's Graphical User Interface is being shifted from tkinter to PyQt5.
Some useful links to get started -- 1.) https://pythonspot.com/pyqt5/
                                                        2.) http://zetcode.com/gui/pyqt5/
                                                        3.) https://blog.manash.me/quick-pyqt5-1-signal-and-slot-example-in-pyqt5-bf502ccaf11d  (blog series)

**Comment by sarthak247** [comment]
Wasn't the GUI supposed to be done using Electron? Any specific reasons for this sudden change of heart?

**Comment by nikhilmehta011** [comment]
Electron.js was never decided. It was taken in consideration as was pyqt and other GUI framewoks. Mentor of the project then finalised PyQt5

**Comment by omi10859** [comment]
@sarthak247 would suggest reading some recent messages on the group i.e slack Groot channel

**Comment by plusminuschirag** [comment]
[PyQt5 GUI Programming with python 3.6:] https://www.youtube.com/playlist?list=PL1FgJUcJJ03uwFW8ys2ov2dffKs3ieGYk

[PyQt] https://www.youtube.com/playlist?list=PLZocUikpczs-Yud2lyFpSNQOvxuPUVBDp


They videos can surely help to transition into pyqt5

**Comment by nikhilmehta011** [comment]
@omi10859 Hey so I am encountering some errors while runnig groot. "Ecxeption in tkinter callback" is flashing. My views are first of all we should switch GUI from tkinter ro PyQt5 then work on these feactures and their bugs

**Comment by plusminuschirag** [comment]
Working on this along with @nikhilmehta011
