### ISSUE TITLE
Groot is running only once

### ISSUE THREAD

**Issue by nikhilmehta011** [omi10859/jarvis#21]
After running gui.py groot windows appears and runs fine after typing suitable input. But it gives error when trying to execute groot the second time. Screen recording of the issue is provided. Kindly check that out.

[screen_recording.zip](https://github.com/omi10859/GROOT/files/2918144/screen_recording.zip)
![20190301113024](https://user-images.githubusercontent.com/35212721/53626504-e2551d80-3c2b-11e9-8763-1f6cdd1cf7ed.gif)

**Comment by plusminuschirag** [comment]
Are you work on it?

**Comment by nikhilmehta011** [comment]
Yes I am

**Comment by omi10859** [comment]
Hey please upload a gif instead of a video file, 
You can convert video to gif online.

**Comment by nikhilmehta011** [comment]
> Hey please upload a gif instead of a video file,
> You can convert video to gif online.

Done. I uploaded video in the first place so that the other contributors can hear the groot answering.
