### ISSUE TITLE
Addition of Cool Features.

### ISSUE THREAD

**Issue by plusminuschirag** [omi10859/jarvis#31]
**Since Groot is heading towards becoming personal assistant. I would like to add very interesting and heavily used features:**

* News about various topics filtered from various credible sources.

* Additional Headlines Feature

**Comment by omi10859** [comment]
Nice idea!!
For news you can go with inshorts

**Comment by plusminuschirag** [comment]
That's great but I was thinking of added  [NEWS](https://newsapi.org/) which provides multiple alternatives of news. It has a simple sign up to get api keys and gives list of all the news along with the sources.

**Comment by arnabsinha99** [comment]
> 
> 
> That's great but I was thinking of added [NEWS](https://newsapi.org/) which provides multiple alternatives of news. It has a simple sign up to get api keys and gives list of all the news along with the sources.

Should we try and code this API from scratch or just use it as it is? It would be a great addition to Groot though!

**Comment by omi10859** [comment]
@arnabsinha99 we can just go with api
