### ISSUE TITLE
Keep my notes!!

### ISSUE THREAD

**Issue by plusminuschirag** [omi10859/jarvis#35]
We need a functionality to keep safe notes for the future use. Groot must find the best way to store them and be reliable as much as it can be.

- **Groot must store it to Google Drive**. Keeping all the documents for master safe and sound. Better if Groot reads it for the master.

- Notes will have a password protection mechanism.

**Comment by omi10859** [comment]
Like the idea
We can save all the data in google docs and then fetch it when asked. While I don't think so we need password protection mechanism.

**Comment by plusminuschirag** [comment]
I will take this issue please.

**Comment by plusminuschirag** [comment]
- Create a Groot Folder in Google Drive
- [Generate client_secrets.json file ](https://help.talend.com/reader/E3i03eb7IpvsigwC58fxQg/ol2OwTHmFbDiMjQl3ES5QAl)

- ![Screenshot from 2019-04-12 17-27-44](https://user-images.githubusercontent.com/29746593/56035789-bcea2200-5d48-11e9-8cf5-2434bdb9543d.png)
- **paste the client_secrets.json file in the same level as Gui.py**

**Comment by plusminuschirag** [comment]
- ***Say Open Notes| Groot Open Notes | Open Docs*  but try to be clear. Say "Open Notes" as it is most clear of all.**

![Screenshot from 2019-04-12 17-35-55](https://user-images.githubusercontent.com/29746593/56036197-db9ce880-5d49-11e9-83fc-342e0d1c11ce.png)


- **Title** - Name of the file and also title of your note
- **Summary** - Stands for the content of file
- **Note Button** - Shows all the notes you have currently created.
- **Save** - Feature Saves the notes

See authenticator.py under NotesLib in modules for more functions implemented inside.
