### ISSUE TITLE
Adding Quick Mail Shooting Capabilities

### ISSUE THREAD

**Issue by plusminuschirag** [omi10859/jarvis#39]
Adding Quick Mail Shooting Capablities in Groot by user email. Would be nice time saving feature and very handy since sometimes convo needs to be done immediately.

**Comment by omi10859** [comment]
It's a nice idea. Do let me know about all the details on how you wish to implement this. 
It should be capable of doing this over voice commands.

**Comment by plusminuschirag** [comment]
Yes this can happen over voice. 
Any mail with SMTP server access can do this. It's best with gmail for now. We can quick shoot mail over voice
