### ISSUE TITLE
add more question and answer  

### ISSUE THREAD

**Issue by omi10859** [omi10859/jarvis#5]
We will use Deep leaning to reply to the user but still, we need to add some more common questions and there answers. 

Hint: You need to make changes in groot.py

**Comment by Manas-kashyap** [comment]
I am taking this task and adding questions , but i have a confusion in the groot.py is open facebook leads to trigeration of other module to open facebook , so , why cant we make three modules , like this in which one we can get answers and others for trigeration of modules , more helpful .

**Comment by omi10859** [comment]
We are not going to add to many questions as soon, We will have a trained model to answer the questions. so I guess adding few more questions in groot.py would not be bad. 
also @Manas-kashyap Please add some command questions only. Thanks

**Comment by omi10859** [comment]
What are the questions you are thinking to add?

**Comment by Manas-kashyap** [comment]
well , i was thinking more like , what does my zodiac sign tell about me today , how do i look today (just to make that person feel good) , some science related questions , whats the day today , any reminder (to be fetched from the previous , firstly they have to enter it )

**Comment by omi10859** [comment]
so for that, we can create different modules and this comes under automation only.
like for reminders, we can use Google API to fetch events (reminders that are already saved in Google calendar) We can also give Groot reminder that we can save and export to google calendar itself.)
